name: lyra_framework
description: Framework to speed up development.
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  uuid: ^3.0.6
  flutter_feather_icons: ^2.0.0+1
  url_launcher: ^6.0.20
  http: ^0.13.4
  sqflite: ^2.0.2
  sqflite_common_ffi: ^2.1.0+2
  path_provider: ^2.0.9
  intl: ^0.17.0
  device_info_plus: ^3.2.3
  path: ^1.8.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter